### ISSUE TITLE
Full Access above 33 using MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [anggrayudi/SimpleStorage#134]
hi MANAGE_EXTERNAL_STORAGE is , i think depricated in android 33 and this is dangerous permission 
did u use SAF or mediquery to get list of files like pdf text etc 
can this be possible now because of google policies images and video easily fetched but Files are not getting in list placed inside download Folder but images is easily availble but pdf are not like we did before walkDir() for get all files now not working any idea how to reolve this or this is now not possible

**Comment by anggrayudi** [comment]
This library can access files via:
* Storage Access Framework. Of course, after the user granted the URI permission via this dialogue:
![Screenshot_20240618_215541](https://github.com/anggrayudi/SimpleStorage/assets/12292380/b13fecb0-5028-4162-9664-fa032425c0c0)

* Full storage access `MANAGE_EXTERNAL_STORAGE` (API 30+ only)
* `uses-permission` tag in Manifest (Android 28 and lower):
  * `android.permission.READ_EXTERNAL_STORAGE`
  * `android.permission.WRITE_EXTERNAL_STORAGE`

This library can handle all of them. It depends on your needs. If your apps are file manager, cleaner, antivirus, etc. then Google may allow you to publish the apps to Play Store. Otherwise, it might get rejected.
