### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by 1stmetro** [anggrayudi/SimpleStorage#2]
I have looked at the help i could find on SimpleStorage but cant seem to get started..

Any help available on implementing this into java, 

selecting folders and files doesn't seem to work and thats before i try to grab the results, as i said im a little stuck right at the start.

Many thanks,

**Comment by anggrayudi** [comment]
Hi @1stmetro, I have released Simple Storage v0.3.0 with Java support. Follow this [documentation](https://github.com/anggrayudi/SimpleStorage/blob/master/JAVA_COMPATIBILITY.md) to use this library in your Java project.

Also please read the latest [README.md](https://github.com/anggrayudi/SimpleStorage/blob/master/README.md) because there are terminology changes on this library.
