### ISSUE TITLE
APK Sample

### ISSUE THREAD

**Issue by akosiatph** [anggrayudi/SimpleStorage#45]
I hope theres a sample apk or demo so we can try how it works on android11

**Comment by anggrayudi** [comment]
For now, just check out this repo and run it on your machine. I will publish the APK to F-Droid soon.

**Comment by TehreemMasooman** [comment]
Please Give the apk with full functional

because no Multiple File is selected yet

**Comment by anggrayudi** [comment]
I finally decided to publish the APK on the release notes because it is more maintainable and requires no approval. For example, the sample APK can be downloaded here:

<img width="1269" alt="Screen Shot 2022-01-25 at 03 19 41" src="https://user-images.githubusercontent.com/12292380/150858531-52b4c995-224b-4bdf-9a7a-a23835355608.png">
