### ISSUE TITLE
Unable to find method com.android.tools.r8.D8Command$Builder

### ISSUE THREAD

**Issue by sandeepvadgama** [anggrayudi/SimpleStorage#51]
Android Studio Arctic Fox | 2020.3.1 Patch 1
OS - macOS 10.15.7

After adding random strings in gradle.properties:

anggrayudi_maven_username=abc
anggrayudi_maven_password=xyz

Still getting below errors

Unable to find method ''com.android.tools.r8.D8Command$Builder com.android.tools.r8.D8Command$Builder.addMainDexRules(java.util.List, com.android.tools.r8.origin.Origin)''
'com.android.tools.r8.D8Command$Builder com.android.tools.r8.D8Command$Builder.addMainDexRules(java.util.List, com.android.tools.r8.origin.Origin)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Re-download dependencies and sync project (requires network)**
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
**Tried Multiple Time didn't work**

**Stop Gradle build processes (requires restart)**
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
**Tried Multiple Time didn't work**

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
**Did't work**

**Comment by anggrayudi** [comment]
I've tried random strings and it worked without issue:

<img width="291" alt="Screen Shot 2021-09-10 at 15 16 22" src="https://user-images.githubusercontent.com/12292380/132822887-186a285e-a969-415c-996c-0378822484ce.png">


But if you want to enable obfuscation, it wont work because the sample code uses [Material Dialogs](https://github.com/afollestad/material-dialogs):

    Execution failed for task ':sample:minifyLocalReleaseWithR8'.
    > com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position:
    Lcom/afollestad/materialdialogs/R$layout;
    copyFolderTo(Landroidx/documentfile/provider/DocumentFile;
    Landroid/content/Context;
    Landroidx/documentfile/provider/DocumentFile;
    ZLjava/lang/String;
    ZLcom/anggrayudi/storage/callback/FolderCallback;)V,
    origin: SimpleStorage/sample/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/localRelease/R.jar:com/afollestad/materialdialogs/R$layout.class

Material Dialogs [should be migrated to AndroidX](https://github.com/afollestad/material-dialogs/issues/2047) to fix this issue. However, if you use this library as a dependency in your project, it will work with obfuscation.
I will consider this is an invalid issue and should be closed.
