### ISSUE TITLE
write access for childs dir on android 11

### ISSUE THREAD

**Issue by 231351** [anggrayudi/SimpleStorage#61]
**What feature you want to suggest?**
[[](https://developer.android.com/training/data-storage/manage-all-files#operations-allowed-manage-external-storage)]

Write access to all internal storage directories⁠, except for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes direct file path access.
 allow to write on these path

**Comment by anggrayudi** [comment]
We can't grant write access to `storage/emulated/0` via SAF folder picker because it is the restriction of Android 11 system itself. All you can do is requesting the user to grant full disk access via `SimpleStorage.requestFullStorageAccess()`. This full disk access can write files with `java.io.File` or direct file path access.
