### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by WORLD8848** [anggrayudi/SimpleStorage#70]
I downloaded the 'Simple Storage' source code.
After that, the source code was executed, and the following error message could be checked.

I wonder if there are any settings you need to run the source code.

It may be cumbersome, but please answer.

Build error message

1. Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'anggrayudi_maven_username' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

2. Caused by: com.vanniktech.maven.publish.MavenPublishConfigurer$MissingVariantException: Invalid MavenPublish Configuration. Unable to find variant to publish named release. Try setting the 'androidVariantToPublish' property in the mavenPublish extension object to something that matches the variant that ought to be published.

3. The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by stefanoberdoerfer** [comment]
These errors (1. and 2.) are not crucial for the compilation. They are only for publishing the library to a maven repo.

You can fix the build by just commenting out these lines:
`build.gradle:30-34` and `app/build.gradle:77-91`

The last one is just a deprecation warning and should not prevent the build to succeed.

**Comment by anggrayudi** [comment]
@stefanoberdoerfer is right. It is used for publishing only. You can use random string for these properties in `gradle.properties` to remove the error.

<img width="278" alt="Screen Shot 2021-11-24 at 06 28 45" src="https://user-images.githubusercontent.com/12292380/143145064-462bcd46-41ef-4977-b973-32a831843eff.png">

Regarding to `kotlin-android-extensions` deprecation usage, for now I will not migrate to Android View Binding, because this library is for demonstration only. Not crucial at all.
