### ISSUE TITLE
Android 11 no data folder

### ISSUE THREAD

**Issue by LSDsl** [anggrayudi/SimpleStorage#81]
**What feature you want to suggest?**
Access to Andriod/data folder without Full Storage Access

**Your solution**
Use grant permission
Some example https://rhmsoft.com/qedit/data.html

**Your current alternative**
Use another lib!?

**Comment by anggrayudi** [comment]
Accessing `storage/emulated/0/Android/data/{yourPackageName}` never requires any storage permission, because you use your own app private directory. You can use `java.io.File` for this path. But accessing other app's package folder requires full storage access. You can achieve it via `SimpleStorage.requestFullStorageAccess()` or via `Intent`:

```kotlin
context.startActivity(Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION))
```

Requesting URI permissions like this is not possible because `Android/data` is hidden by the SAF folder picker:
```kotlin
storageHelper.requestStorageAccess(expectedBasePath = "Android/data")
```

**Comment by LSDsl** [comment]
In example even after requestFullStorageAccess Andrdoi/data folder is not visible. Could you help with this?

**Comment by anggrayudi** [comment]
Oh, you are right. I've just tested it. Directory `storage/emulated/0/Android/data` is visible in Android Studio File Explorer, but returns null with full disk access:

<img width="1611" alt="Screen Shot 2022-01-30 at 00 32 55" src="https://user-images.githubusercontent.com/12292380/151671188-282cf148-9e54-46e6-919f-4669ce9a4b47.png">

Sadly, requesting full disk access is the last option. I have no solution on this. Maybe Google wants the SAF to be more secure, to prevent malicious apps from modifying other app's system files.

**Comment by LSDsl** [comment]
You can check how QuickEdit do this. It ask full disk access and also SAF as I understand. And have access to any data sub-dir.
